pages:
  stage: deploy
  image: python:3.13.9-slim-trixie
  script:
    - apt update
    - apt install -qy mkdocs-material mkdocs-material-extensions python3-mdx-math katex
    - mkdocs build --site-dir public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.cache/ 
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "Development"
