site_name: From Code to Robot
site_description: Project Documentation
site_author: Institute of Industrial and Control Engineering (IOC) - Universitat Politècnica de Catalunya
site_url: https://teaching.ioc.upc.edu/from-code-to-robot/
use_directory_urls: true

docs_dir: docs

theme:
  name: material
  language: en

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: ca
          name: Català
          build: true
        - locale: es
          name: Español
          build: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - javascripts/katex-init.js
  