site_name: RS-Toolbox Docs
site_description: Documentation for RS-Toolbox
site_author: RS-Toolbox

docs_dir: RS-Toolbox_docs

theme:
  name: material
  language: en

plugins:
  - search
  - redirects:
      redirect_maps:
        index.md: Curriculum.md

extra_javascript:
  - js/mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math

