site_name: RS-Toolbox Docs
site_description: Documentation for RS-Toolbox
site_author: RS-Toolbox

docs_dir: RS-Toolbox_docs

theme:
  name: material
  language: en

plugins:
  - search

extra_javascript:
  - js/mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math

nav:
  - Home: Curriculum.md
  - Demo: Demo.md
  - Installation: Installation.md
  - Basics:
      - Cells: 0.Basics/Cells.md
      - Matrix manipulation: 0.Basics/Matrix_manipulation.md
      - Structures: 0.Basics/Structures.md
      - Symbolic Math toolbox: 0.Basics/Symbolic_Math_toolbox.md
  - Modelling:
      - Tutorial:
          - Modelling with RS toolbox: 1.Modelling/Tutorial/Modelling_with_RS_toolbox.md
          - Transforms: 1.Modelling/Tutorial/Transforms.md
      - Exercises:
          - Exercise 1-1: 1.Modelling/Exercise/Exercise-1-1.md
          - Exercise 1-2: 1.Modelling/Exercise/Exercise-1-2.md
          - Exercise 1-3: 1.Modelling/Exercise/Exercise-1-3.md
      - Solutions:
          - Solution 1-1: 1.Modelling/Solutions/Solution-1-1.md
          - Solution 1-2: 1.Modelling/Solutions/Solution-1-2.md
          - Solution 1-3: 1.Modelling/Solutions/Solution-1-3.md
          - Solution 1-1-4 (reverse): 1.Modelling/Solutions/Solution_1_1_4_reverse.md
  - Kinematics:
      - Tutorial:
          - Forward Kinematics: 2.Kinematics/Tutorial/Forward_Kinematics.md
          - Inverse Kinematics: 2.Kinematics/Tutorial/Inverse_Kinematics.md
          - Joint Space Trajectory Planning: 2.Kinematics/Tutorial/Joint_Space_Trajectory_Planning.md
      - Exercises:
          - Exercise 2-1: 2.Kinematics/Exercises/Exercise-2-1.md
          - Exercise 2-2: 2.Kinematics/Exercises/Exercise-2-2.md
          - Exercise 2-3: 2.Kinematics/Exercises/Exercise-2-3.md
          - Exercise 2-4: 2.Kinematics/Exercises/Exercise-2-4.md
      - Solutions:
          - Solutions 2-1: 2.Kinematics/Solutions/Solutions-2-1.md
          - Solutions 2-2: 2.Kinematics/Solutions/Solutions-2-2.md
          - Solutions 2-3: 2.Kinematics/Solutions/Solutions-2-3.md
          - Solutions 2-4: 2.Kinematics/Solutions/Solutions-2-4.md
  - Differential Kinematics:
      - Tutorial:
          - Inverse Kinematic Algorithm: 3.Differential Kinematics/Tutorial/Inverse_Kinematic_Algorithm.md
          - Jacobians: 3.Differential Kinematics/Tutorial/Jacobians.md
          - Manipulability: 3.Differential Kinematics/Tutorial/Manipulability.md
      - Exercises:
          - Exercise 3-1: 3.Differential Kinematics/Exercise/Exercise-3-1.md
          - Exercise 3-2: 3.Differential Kinematics/Exercise/Exercise-3-2.md
          - Exercise 3-3: 3.Differential Kinematics/Exercise/Exercise-3-3.md
      - Solutions:
          - Solutions 3-1: 3.Differential Kinematics/Solutions/Solutions-3-1.md
          - Solutions 3-2: 3.Differential Kinematics/Solutions/Solutions-3-2.md
          - Solutions 3-3: 3.Differential Kinematics/Solutions/Solutions-3-3.md
  - Dynamics:
      - Tutorial:
          - Dynamics (Lagrange Formulation): 4.Dynamics/Tutorial/Dynamics_Lagrange_Formulation.md
          - Parameterization and Identification: 4.Dynamics/Tutorial/Parameterization_and_Identification.md
      - Exercises:
          - Exercise 4-1: 4.Dynamics/Exercise/Exercise-4-1.md
          - Exercise 4-2: 4.Dynamics/Exercise/Exercise-4-2.md
          - Exercise 4-3: 4.Dynamics/Exercise/Exercise-4-3.md
      - Solutions:
          - Solutions 4-1: 4.Dynamics/Solutions/Solutions-4-1.md
          - Solutions 4-2: 4.Dynamics/Solutions/Solutions-4-2.md
          - Solutions 4-3: 4.Dynamics/Solutions/Solutions-4-3.md
  - Control:
      - Tutorial:
          - Control Schemes: "5.Control/Tutorial/Control Schemes.md"
      - Solutions:
          - Exercise 5-1: 5.Control/Solutions/Exercise-5-1.md
