function B = B_sym_subs(in1)
%B_sym_subs
%    B = B_sym_subs(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Jan-2026 20:04:06

q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q3);
t3 = q2.*2.0;
t4 = t2.*3.75e-1;
t5 = t4+2.525e-1;
B = reshape([t4+cos(q3.*2.0+t3).*1.2375e-1+cos(q2+q3).*4.5e-1+cos(q3+t3).*3.75e-1+cos(q2).*1.35+cos(t3).*4.9875e-1+1.326666666666667,0.0,0.0,0.0,t2.*7.5e-1+1.255,t5,0.0,t5,2.525e-1],[3,3]);
end
