function C_comp = C_sym_subs_comp(in1,in2)
%C_sym_subs_comp
%    C_comp = C_sym_subs_comp(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Jan-2026 20:04:12

q2 = in1(2,:);
q3 = in1(3,:);
qd2 = in2(2,:);
qd3 = in2(3,:);
t2 = sin(q3);
t3 = q2+q3;
t4 = q2.*2.0;
t6 = sin(t3);
t7 = q2+t3;
t10 = t3.*2.0;
t8 = sin(t7);
t9 = t6.*2.25e-1;
t11 = sin(t10);
t12 = t11.*1.2375e-1;
C_comp = reshape([-qd3.*(t2.*1.875e-1+t8.*1.875e-1+t9+t12)-qd2.*(t8.*3.75e-1+t9+t12+sin(q2).*6.75e-1+sin(t4).*4.9875e-1),0.0,0.0,0.0,qd3.*t2.*-3.75e-1,0.0,0.0,0.0,0.0],[3,3]);
end
