function C = C_sym_subs(in1,in2)
%C_sym_subs
%    C = C_sym_subs(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Jan-2026 20:04:06

q2 = in1(2,:);
q3 = in1(3,:);
qd1 = in2(1,:);
qd2 = in2(2,:);
qd3 = in2(3,:);
t2 = sin(q2);
t3 = sin(q3);
t4 = q2+q3;
t5 = q2.*2.0;
t7 = sin(t5);
t8 = t2.*6.75e-1;
t9 = t3.*1.875e-1;
t10 = sin(t4);
t11 = q2+t4;
t15 = t4.*2.0;
t12 = sin(t11);
t13 = t7.*4.9875e-1;
t14 = t10.*2.25e-1;
t16 = sin(t15);
t17 = t12.*1.875e-1;
t18 = t12.*3.75e-1;
t19 = t16.*1.2375e-1;
t20 = t9+t14+t17+t19;
t22 = t8+t13+t14+t18+t19;
t21 = qd1.*t20;
t23 = qd1.*t22;
C = reshape([-qd3.*t20-qd2.*t22,t23,t21,-t23,qd3.*t3.*-3.75e-1,qd2.*t3.*3.75e-1,-t21,t3.*(qd2+qd3).*(-3.0./8.0),0.0],[3,3]);
end
