function G = G_sym_subs(in1)
%G_sym_subs
%    G = G_sym_subs(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Jan-2026 20:04:07

q2 = in1(2,:);
q3 = in1(3,:);
t2 = conj(q2);
t3 = conj(q3);
t4 = conj(t2)+conj(t3);
t5 = cos(t4);
t6 = t5.*7.3575;
G = [0.0;t6+cos(conj(t2)).*2.20725e+1;t6];
end
